### ISSUE TITLE
Timeout Error on request

### ISSUE THREAD

**Issue by kvermeille** [drudge/passport-facebook-token#12]
There seems to be a bug that causes the system to hang forever.

**Comment by jakubknejzlik** [comment]
Hi, I've run into similar issue. But it's hard to investigate, because it happens after a while (or after few hundreds of authorization requests). I'll share more, when I found it.

**Comment by jakubknejzlik** [comment]
OK, I've managed to get more detailed info about our issue and this package is the cause 👍

**Comment by divyekhanna** [comment]
@jakubknejzlik What's the cause? I'm experiencing the same. One error per many authentication requests (hundreds). I get an ETIMEDOUT response

**Comment by jakubknejzlik** [comment]
@divyekhanna we found out that it wasn't problem with this package, but it was during downloading user's profile image.

**Comment by divyekhanna** [comment]
@jakubknejzlik What did you do to fix it?

**Comment by jakubknejzlik** [comment]
we fixed our internal code

**Comment by divyekhanna** [comment]
Could you tell me what you fixed specifically? I'm pretty sure it is being generated inside `FacebookTokenStrategy`. The error is thrown inside `passport-facebook-token`:

```
this._oauth2.get(profileURL, accessToken, function (error, body, res) {
        if (error) return done(new _passportOauth.InternalOAuthError('Failed to fetch user profile', error));
```

Thanks!

**Comment by jakubknejzlik** [comment]
Unfortunately no. As I said before, the fix was in our internal (private) code.

**Comment by Vilintritenmert** [comment]
`{ Error
    at /var/www/onekafe.global/node_modules/passport-facebook-token/lib/index.js:155:32
    at ClientRequest.<anonymous> (/...l/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'InternalOAuthError',
  message: 'Failed to fetch user profile',
  oauthError: 
   { Error: connect ETIMEDOUT 157.240.21.16:443
       at Object.exports._errnoException (util.js:1050:11)
       at exports._exceptionWithHostPort (util.js:1073:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '157.240.21.16',
     port: 443 } }
`
node v7.10.1
Ubuntu 17.04

Maybe not right, but this error started with "when you added socket.io to the project.

Need something else ?
