### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by maziyarpanahi** [drudge/passport-facebook-token#14]
Hi,

I am trying to use this module so in future I get the access_token from mobile devices(whether from native library or third-party SDK) and authenticate/authorize users.

For test, I am using passport-facebook for my browser-based app and it works perfectly. It brings back a token, is this the access token this module needs? Because I used all sort of access_token and I always get Unauthorized 401 error.

Please guide me to use this module as it's necessary for people who are developing mobile apps and have their backends on NodeJS+PassportJS. A simple example of getting access_token and a sample post URL with JSON would mean a lot.

Thanks.

**Comment by tonymuu** [comment]
The problem for me was that I used "token" instead of "access_token" as my parameter's name... If you tried everything above, make sure you have the parameter's name down as "access_token"
