### ISSUE TITLE
using two different app ids

### ISSUE THREAD

**Issue by tidyware** [drudge/passport-facebook-token#15]
We are using a single server instance for two different facebook app ids used on our javascript client (one with our domain name and one with localhost as the site url in the facebook developers console).

Is there a way to have the clientID and clientSecret set per request rather than when the service starts?

**Comment by skpullano** [comment]
So i have been working with this for days and i am stuck. i am always getting a 401 response however my code goes to the findOrCreate call back and executes the done method with err being null and user populated however it still returns 401. I am trying to trace down the done method to see why it returns 401. Any help tracing here that done method goes to?

**Comment by ghaiklor** [comment]
@Ph3n1x 

> And even more interesting, why do we have to set the clientID and clientSecret?

It's required for passport-oauth2 strategy, which is our super-class.

@tidyware you can instantiate strategy only once and then just pass access_token from FB. That's all what we need.
