### ISSUE TITLE
Do you have an example?

### ISSUE THREAD

**Issue by nitsingh** [drudge/passport-facebook-token#20]
I am new to passport and passport-facebook-token usage. The passport-facebook-token fits my usecase perfectly. Just an example my give the needed push

**Comment by loolooii** [comment]
Yes, an example would be very nice :)

**Comment by simondelliott** [comment]
+1

**Comment by demisx** [comment]
+1 Otherwise not very clear how this is different from the original `passport-facebook'`

**Comment by alanjames1987** [comment]
+1

**Comment by Zeralith** [comment]
+1

A simple example node application with an example curl command showing how to make the POST to login, showing the URL and query string, would be really helpful and amazing.

A basic user authentication system/model, doing everything in memory without sessions, should be fine for the example.

Thank you for making this module... just again, needs more documentation/examples to really make it next level :)

**Comment by ghaiklor** [comment]
@Zeralith and others, did you read README https://github.com/drudge/passport-facebook-token#authenticate-requests ?

You just need make POST request to your route with  Facebook `access_token` field. And in this route you call `authenticate` method.

**Comment by ztrange** [comment]
As I understand it, the difference between passport-facebook and passport-facebook-token is analogous to the difference between service-directed login operation and client-directed login operation in Azure Mobile Services Identity capabilities:

https://msdn.microsoft.com/en-us/library/azure/jj710108.aspx

**Comment by ghaiklor** [comment]
@ztrange yeah, smth like that. `passport-facebook` working on with full OAuth2 flow. Starting from create session and ending with callback URLs, etc...

`passport-facebook-token` works without that, just access_token from FB in POST request. It's helpful when you have, for instance, REST API, where you can't manage OAuth2 flow, but you still need to work with passport and get some profile from social networks.

**Comment by morenoh149** [comment]
There is a minimal example floating around https://github.com/philipbrack/express-passport-facebook-token-example I'm currently looking into fleshing it out to support user registration.

@ghaiklor is it possible to register a user for a service using passport-facebook-token?

**Comment by ghaiklor** [comment]
@morenoh149 yes

You need to authenticate user via Facebook OAuth somewhere (mobile phone, website, whatever) and grab access token from the result.

With this token you can go to your API where passport-facebook-token configured and provide it in a request. Your API can go then with this token to fetch Facebook profile and register user in your db with its data.

**Comment by morenoh149** [comment]
Yes I see that explained here as well https://stackoverflow.com/questions/20929092/passport-js-passport-facebook-token-strategy-login-through-js-sdk-and-then-aut/24474900#24474900 thanks
