### ISSUE TITLE
Long-lived Facebook Token

### ISSUE THREAD

**Issue by codeHatcher** [drudge/passport-facebook-token#22]
Will there be any support for returning a long-lived Facebook Token as well? Or even a helper function that can be used to retrieve one from FB?

**Comment by trex005** [comment]
I also needed this, so I have made the modifications myself.  I have submitted a pull request.

**Comment by demisx** [comment]
+1

**Comment by evenbrenna** [comment]
+1 Would love to see this implemented!

**Comment by drudge** [comment]
There is a pull request that won't merge cleanly, if you want to fix that up I'll merge it in.
