### ISSUE TITLE
Extended permissions?

### ISSUE THREAD

**Issue by anonrig** [drudge/passport-facebook-token#30]
Does this project include extended permissions for facebook including email?

**Comment by ghaiklor** [comment]
@anonrig This module implements only authorize via already generated access tokens from frontend. So extended permissions should be granted on access token generation flow.

**Comment by anonrig** [comment]
@ghaiklor even though the access token is granted an email access, it would be nice to include some basics like photos, email, name, surname as default.

**Comment by tharrington** [comment]
I receive a token via an iOS app then pass the token to my server, as recommended. Then my node app authenticates:

passport.use(new FacebookTokenStrategy({
      clientID: '833254570056647',
      clientSecret: '2919aaae6ce1662b5840c2c83e7fbc5e'
    },
    function(accessToken, refreshToken, profile, done) {
      console.log('using strat....');
      console.log('profile: ' + JSON.stringify(profile));
      User.findOne({ facebookId: profile.id }, function (err, user) {

        return done(err, user);
      });
    }
  ));

The profile does not include an email: 
{"provider":"facebook","id":"some id","displayName":"name name","name":{"familyName":"","givenName":"","middleName":""},"gender":"","emails":[{"value":""}],"photos":[{"value":"https://graph.facebook.com/sadfdsf/picture?type=large"}],"_raw":"{\"name\":\"name name\",\"id\":\"someid\"}","_json":{"name":"Hey My name","id":"someid"}}

despite asking for the following permissions in the app:
$cordovaFacebook.login(["public_profile", "email", "user_friends"])

**Comment by ghaiklor** [comment]
@tharrington are you sure that token is granted for email getting ? You can check it via Graph API. I have a lot applications written with Swift and everything works fine. You didn't get email in the profile, because email is empty in response from Facebook, so I can't parse it.

**Comment by tharrington** [comment]
@ghaiklor if I use the graph explorer and do a /me request I just get the id and name. However, if I pass in me?fields=email I get the email and the id. So it seems like I have asked for both.

**Comment by ghaiklor** [comment]
@tharrington you can pass `profileFields` array info config object. See here - https://github.com/drudge/passport-facebook-token/blob/master/index.js#L141

```javascript
new FacebookTokenStrategy({
  profileFieds: ['emails']
});
```

**Comment by irokhes** [comment]
Hi,

I have the same issue. it's not returning the email but if I check the same token in Graph explorer Api return email (https://developers.facebook.com/tools/explorer?method=GET&path=me%3Ffields%3Did%2Cname%2Cemail&version=v2.4)

I tried adding profileFieds: ['emails'] but doesn't make any different.

Does anyone know what is the problem?

Thanks!

**Comment by ghaiklor** [comment]
@irokhes just published few releases and checked all the problems above. Everything is works. Closing.
