### ISSUE TITLE
What's The format of object JSON? 

### ISSUE THREAD

**Issue by rafaelmnz** [drudge/passport-facebook-token#32]
Hello, 
What's format of object son that i need to send to server? Because The server return this message for me:  "JSON text did not start with array or object and option to allow fragments not set."

I am trying to use this module so in future I get the access_token from mobile devices(whether from native library or third-party SDK) and authenticate/authorize users.

For test, I am using passport-facebook for my browser-based app and it works perfectly. It brings back a token, is this the access token this module needs? Because I used all sort of access_token and I always get Unauthorized 401 error.

Please guide me to use this module as it's necessary for people who are developing mobile apps and have their backends on NodeJS+PassportJS. A simple example of getting access_token and a sample post URL with JSON would mean a lot.

Thanks.

I'm passing with this format: 

{
    "acess_token" = CAAX0gvob580BADKzfxvrX22ZBq4KvOZC6KN72M4BL4y1QdjKrxfNP1KFHgx0kI8BPIsESnHacqSZAu3HjGweOuaZAMG6RRcabJ0q086o5uAvHJQwu7klpN6RH682w2hhFZAhBeSBZCCkXKJLByDeasaPS8q55VFo7zKKvwPcaFlA3raozMit80r8ekZBltKgj3Bq6yAdWKHNRRBS9HZCwpC5Im9vkChXIHh7TZBuO97fytwZDZD;
}

OR 

ttp://192.168.1.2:3000/auth/facebook/token?acess_token=CAAX0gvob580BALuSeZBEnZCaX1gOfBENXw8DguDhiU2ItP51fsC2T8WamyqY6KNGTi6mOLXfKOKAZBDiqzSlK3PWeTR56Ng1yR0cXXOPSTrLbprEEJZC0yMnZBGb4FKi36jaIRNJLtNgZAInTW52Pa1RKj0FHIjW72p5vHY8XcZBatwaWTvOe97sT3yySUC0EZCTtZBlNCbCWzVUqnGA6kqUCn8mPudXzxnLvjOGUZAZBZBRZBgZDZD

**Comment by ghaiklor** [comment]
@rafaelmnz we have Readme when explaining what request should contain.

```
GET /auth/facebook/token?access_token=<TOKEN_HERE>
```
