### ISSUE TITLE
Cyclic redirection on auth page

### ISSUE THREAD

**Issue by Yakimun** [drudge/passport-facebook-token#33]
Using LoopBack. Passport configuration:
```json
{
  "facebook-token": {
    "module": "passport-facebook-token",
    "authorizationURL": "/auth/facebook-token",
    "tokenURL": "/auth/account",
    "clientID": 123,
    "clientSecret": "456"
  }
}
```
I have cycled redirect when I try to authorize.
Following parameters are added to the address of the page:
`response_type=code&redirect_uri=&client_id=123`

**Comment by ghaiklor** [comment]
@Yakimun do you trying to use this module on client-side ? I'm asking because this module is designed only for servers that don't have views. You just pass already obtained `access_token` that you got before. Here is nothing to do with redirects and obtaining OAuth2.0 tokens.

**Comment by Yakimun** [comment]
No. I have route `/auth/facebook-token` (from configuration) and I get redirect to `/auth/facebook-token` (302) when I try to request it.

**Comment by ghaiklor** [comment]
@Yakimun I just checked all the edge-cases in my project that uses the latest version of this module. Everything works.

```
GET /v1/auth/facebook?access_token=<FACEBOOK_ACCESS_TOKEN>
```

returns me parsed profile so I can register it in database and proceed to next step.

I think that you need to override default verified method, for instance:

```javascript
passport.authenticate('facebook-token', function(error, user, info) {
  // do your stuff here with user profile
  res.ok();
});
```

**Comment by ghaiklor** [comment]
I think that issue in default behaviour of `verified` method. If you override this, as it says in documentation, then it works fine. Closing.
