### ISSUE TITLE
profile.displayName is returning empty string, not concatenation of fullname

### ISSUE THREAD

**Issue by JoeParrinello** [drudge/passport-facebook-token#37]

**Comment by ghaiklor** [comment]
@JoeParrinello Facebook has a separate field called `name` for this purpose. If this field is not defined then it will be empty.

**Comment by Salakar** [comment]
@JoeParrinello  @ghaiklor having the same issue also, checked the profile json response and the name field isn't returned, just `id`, `first_name`, `last_name` and `email` is returned from facebook.

**Comment by ghaiklor** [comment]
@Salakar I'll try to reproduce this issue when I have time.

**Comment by Boeije** [comment]
@JoeParrinello I had the same issue.
you can add an extra property in the config next to clienID and clientSecret:
profileFields: ['id', 'displayName', 'name', 'gender', 'link', 'photos', 'emails']
It is default ['id', 'name', 'emails']

If you don't ask for the information, Facebook will not give it to you.
Maybe it's a good idea to add this to the readme?

**Comment by JoeParrinello** [comment]
@Boeije that makes absolute sense! Good find.
