### ISSUE TITLE
Use OAuth2 standard RFC 6750 for accepting bearer (access) tokens instead of non-standard header field

### ISSUE THREAD

**Issue by tato123** [drudge/passport-facebook-token#41]
Currently the project supports receiving access tokens from a non-compliant header field access_token

```
this._accessTokenField = options.accessTokenField || 'access_token';

...
...

let accessToken = (req.body && req.body[this._accessTokenField]) || (req.query && req.query[this._accessTokenField]) || (req.headers && req.headers[this._accessTokenField]);
```

However to be compliant to the OAuth2 spec (which this library seems to support given the fb api version) by default the library should accept a header called Authorization with the following format:

```
Authorization: Bearer <<access_token_goes_here>>
```
i.e. 
```
Authorization: Bearer mF_9.B5f-4.1JqM
```

The biggest change would be receiving and parsing the access token and ignoring the string "Bearer"

I would be willing to make this change, just want to make sure that its acceptable and there isn't any reason not to.

**Comment by ghaiklor** [comment]
@tato123 hi, you can do this, but don't forgot about backward-compatibility. Someone can use `access_token` in headers.

**Comment by drudge** [comment]
Agreed. I'm willing to accept a PR that introduces the bearer token functionality in addition to what is supported today.

**Comment by tato123** [comment]
Following up on this, a pull request has been submitted and is pending review

**Comment by ghaiklor** [comment]
@tato123 great, I'll merge this soon. I see that existing tests are not failing, so we can merge it.
