### ISSUE TITLE
strategy for authenticating with Facebook using the code returned

### ISSUE THREAD

**Issue by avanttech** [drudge/passport-facebook-token#43]
Hi, I'm not sure which strategy to follow to fulfill this facebook login flow: "Login on Client, API Calls from Server" or "Login on Client, API Calls from Client or Server". Essentially the client (mobile webview) would have initiated the Ouath flow with its callback that'll receive code and then have to use another GET https://graph.facebook.com/v2.3/oauth/access_token? client_id={app-id}&amp;redirect_uri={redirect-uri}&amp;client_secret=app-secret}&amp;code={code-parameter}. to get access token. Can this passport module be used for this? and also does it implement CSRF protection. Kindly point me to the right strategy/module to use?

**Comment by ghaiklor** [comment]
@avanttech this module is used for "Login on Client, API Calls from Server". You must retrieve FB access token from the client and then send this token to the server, where this module get to work. It just takes access token that you sent and trying to login with this token from the server, parsing profile and registering user on the server.

**Comment by avanttech** [comment]
Hi ghaiklor, Thanks for the response. So, essentially that intermediate step to get access_token from authorization code has to be performed internally before accessing this strategy to get authenticated. kindly explain why authorization code to access_token step is not supported - any reasons or in future if this could be integrated as well? We could request for either access_token or auth code from FB depending on the design & security.

**Comment by ghaiklor** [comment]
@avanttech this flow was originally developed for cases, when you have REST API and do not have any possibilities to make OAuth flow with URL callbacks, etc... If you have another context with URL callback on the backend then better to check `passport-facebook` package which is support this.
