### ISSUE TITLE
Allow clients to specify size of profile image

### ISSUE THREAD

**Issue by Maximization** [drudge/passport-facebook-token#45]
Would you be willing to extend the library to allow for optionally setting the size of the profile image? Aside from type=[small, normal, album, large] the endpoint accepts width and height parameters which are rounded to the nearest available dimensions https://developers.facebook.com/docs/graph-api/reference/user/picture/. From my tests I saw that you can get a picture as big as 1520 by 1520 which results in a much better quality than the large version.

**Comment by ghaiklor** [comment]
@Maximization feel free to create a PR and I'll publish new version as soon as it will be merged.

**Comment by Maximization** [comment]
@ghaiklor Great, will do so one of these days :+1:

**Comment by ghaiklor** [comment]
@Maximization published under 3.2.0
