### ISSUE TITLE
500 InternalOAuthError: Failed to fetch user profile

### ISSUE THREAD

**Issue by whispers16** [drudge/passport-facebook-token#47]
Hi, I've got a problem, I'm new at this, when I try to send a token through this callback that I defined localhost:3000/auth/facebook-token/callback?access_token=<Access token I get from facebook> the result is the following error:

500 InternalOAuthError: Failed to fetch user profile
   at C:\adminEasy\loopback-angular-admin\node_modules\passport-facebook-token\lib\index.js:152:32
   at passBackControl (C:\adminEasy\loopback-angular-admin\node_modules\oauth\lib\oauth2.js:123:9)
   at IncomingMessage.<anonymous> (C:\adminEasy\loopback-angular-admin\node_modules\oauth\lib\oauth2.js:143:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickDomainCallback (node.js:381:11)
   at process.<anonymous> (C:\adminEasy\loopback-angular-admin\node_modules\async-listener\index.js:19:15)

I have tested the token in Graph API Explorer of facebook, and the token is right! but I don't get it! can you help me?

**Comment by ghaiklor** [comment]
@whispers16 there is no callbacks in this module. You must send access token direct to route.

If you bind passport route to `auth/facebook-token` for instance then you should send access token to `auth/facebook-token?access_token=<TOKEN>`.

**Comment by whispers16** [comment]
@ghaiklor I binded ```auth/facebook-token``` route and did the same ```auth/facebook-token?access_token=<I get from facebook>```  but I get the same error :(

**Comment by ghaiklor** [comment]
@whispers16 I'll check this on one of my project now and reply to you soon.

**Comment by ghaiklor** [comment]
@whispers16 Just checked and works great on Sails framework.

**Comment by whispers16** [comment]
@ghaiklor I found the problem, it is because I'm using loopback as my backend framework, and I'm using loopback-component-passport, and I needed to set up the providers.json file with this new strategy.

but now I've got another problem, when I send the facebook access token, I'm reciving a cookie with an access token, but it looks like it's a signed token or something like that, the problem is that my api (with loopback) needs that access token to access to any resource in the backend,and I can't access.

do you have any idea??

thank you

**Comment by clockworkgr** [comment]
The method  to unsign the cookie/token is discussed here:

https://github.com/strongloop/loopback-component-passport/issues/83

**Comment by veebuv** [comment]
I'm a little confused, where do i get access to the token in  auth/facebook-token?access_token=<I get from facebook>.

If im using this to sign in , how can i already have access to it.

Please help me out, unless i'm taking this in a very wrong way

**Comment by ghaiklor** [comment]
@veebuv you must get access token on the client-side. This package accepts already grabbed access token from facebook. This package is developed for REST API servers for simplicity of getting and linking user profiles in your app.
