### ISSUE TITLE
InternalOAuthError: Failed to fetch user profile

### ISSUE THREAD

**Issue by zabojad** [drudge/passport-facebook-token#49]
Hi there !

I thought I've correctly setup the passport-facebook-token. But unfortunately I get this:
```
InternalOAuthError: Failed to fetch user profile
    at blablabla/node_modules/passport-facebook-token/lib/index.js:152:32
    at passBackControl (blablabla/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (blablabla/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
To describe what I do: I have a cordova client application that gets (successfully) an access token and sends it to my node.js REST API (protected with passport-facebook-token) within the Authorization HTTP header like this:

```Authorization: Bearer access_token```

I've tried to base64 encode the token but it doesn't change anything...

What could I miss here ?

**Comment by ghaiklor** [comment]
@zabojad try to send access token via POST in `access_token` field. Did it pass ?

**Comment by zabojad** [comment]
@ghaiklor it doesn't throw an InternalOAuthError but it sends back a 401 :(...

**Comment by zabojad** [comment]
@ghaiklor And if I try sending with GET, I get this again:
```
InternalOAuthError: Failed to fetch user profile
    at blablabla/node_modules/passport-facebook-token/lib/index.js:152:32
    at passBackControl (blablabla/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (blablabla/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
I don't understand why POST doesn't endup the same...

Just a question: in the configuration, app secret is the hashkey we generate when creating the Fb app right ?

**Comment by ghaiklor** [comment]
> app secret is the hashkey we generate when creating the Fb app right ?

Yes, just copy-pasted credentials from your Facebook app. Provide here your full request with url and body.

**Comment by zabojad** [comment]
OK, I was not using the right app secret... Sorry for posting this dumb issue...

By the way, how are you managing (server-side) your users that logged in into your application via Fb ? Do you store their access token or just their fb id ?

**Comment by zabojad** [comment]
And another question: the profile object returned by passport-facebook-token contains the name and the picture of the user... Can it get the email too and if yes, how?

Thanks !

**Comment by ghaiklor** [comment]
> Do you store their access token or just their fb id ?

No, our work is just parse profile and send you all the information about the user.

> Can it get the email too and if yes, how?

Your access token must have rights to get email from profile.

**Comment by whispers16** [comment]
@ghaiklor there's any way to return a JSON instead than a cookie, and in what part of the code the cookie is set up?

**Comment by zabojad** [comment]
@ghaiklor everything works fine at my end. You can close this ticket, thank you for your support :)!

**Comment by ghaiklor** [comment]
@whispers16 it returns JSON, don't get it. Create separate issue with your question.
