### ISSUE TITLE
InternalOAuthError: Failed to fetch user profile

### ISSUE THREAD

**Issue by wassimz** [drudge/passport-facebook-token#50]
Hi,
the plugin work fine when I supply a correct facebook token. But when I test it with an expired/wrong token, it throw this exception:
`InternalOAuthError: Failed to fetch user profile`
 Is it normal ?? Why not returning just error code when the token is incorrect ??
How can I catch this exception ?? I have already added a callback to catch the exception but it was never called. I got just the exception returned from the server.

Thanks

**Comment by ghaiklor** [comment]
@wassimz it because it returns an error, take a look - https://github.com/drudge/passport-facebook-token/blob/master/src/index.js#L113

**Comment by wassimz** [comment]
@ghaiklor Thanks for your reply. Yes i seen it. But how can i intercept this error. I am using it with express to build a Rest api. Still i can not catch this error in order to return a correct message to the user. Thanks for your help.

**Comment by wassimz** [comment]
Sorry. The solution was very simple. Juste to catch the error I done it like this:

`router.post('/auth/facebook/token',
            passport.authenticate('facebook-token', {session: false}),
            function (err, req, res, next) {
                if (err) {
                    return ....
                }
                next();
            },
            serializeUser, returnHttpResponse);`

Thanks for this great plugin
