### ISSUE TITLE
Graph API v2.0 is deprecated

### ISSUE THREAD

**Issue by nessche** [drudge/passport-facebook-token#55]
I have received this morning a notice from FB that my application is still using methods from v2.0 which will be deprecated on Aug 8th. I may be now barking at the wrong tree, but shouldn't calls to `https://graph.facebook.com/oauth/access_token` be versioned as well (like `https://graph.facebook.com/v2.4/me`)?

**Comment by nessche** [comment]
I have added a configurable version information to all graph URLs and at least it does not break the current functionality. I can create a PR if you are interested in it...

**Comment by ghaiklor** [comment]
@nessche yeah, sure. Create a PR and I'll publish a package then.
