### ISSUE TITLE
Creating a session with passport-facebook-token

### ISSUE THREAD

**Issue by Bartozzz** [drudge/passport-facebook-token#58]
`Node.js version` : **latest**
`Library version` : **latest**
`Passport version` : **latest**

---

I am creating an API that will be used by native, mobile apps and an auth system with `passport-facebook-token`. In some cases, I need to log-in twice to create a session. I am testing my API with Postman. I’ve noticed that at the first call at `/auth/facebook/token` it creates a Cookie with a `sessionId` parameter and returns:

```
HTTP/1.1 200 OK
{
    success : true,
    message : "User logged in",
}
```

… but when I am trying to request a route which has the `isUserAuthorized` middleware (`req.isAuthenticated()`), it says that the user is not logged in. Then I need to call the `auth/logout` route and log-in again in order to make everything work correctly. The strange thing is that the `auth/logout` route also makes usage of the `isUserAuthorized` middleware. I am not sure if it’s a problem with `passport-facebook-token` or with my implementation, but I need to resolve this issue ASAP.

### isUserAuthorized middleware:

```javascript
export default ( req, res, next ) => {
    if ( req.isAuthenticated() )
        return next();

    res.status( 401 ).send( {
        success : false,
        message : "User not logged in",
    } );
};
```

### `/auth/facebook/token` route:

At the begining it was a `POST` route, but it was not working at all. When I was trying to send `POST` data it was redirecting me to an unexisting url (`/auth/facebook/undefined` if I remember well). I am sending `access_token` as a query parameter now, it works fine. `req.login` and `req.user` are provided by `passport`:

```javascript
app.get( "/auth/facebook/token", passport.authenticate( "facebook-token" ), ( req, res ) => {
    req.login( req.user, error => {
        if ( error ) {
            return res.json( {
                success : false,
                error   : error,
            } );
        }

        res.json( {
            success : true,
            message : "User logged in",
        } );
    } );
} );
```

### `/auth/logout` route:

```javascript
app.get( "/auth/logout", isUserAuthorized, ( req, res ) => {
    req.logout();

     res.json( {
         success : true,
         message : "User logged out",
     } );
} );
```

### Express app config:

Just pasting stuff used by passport/etc., not all the code because it’s a big and complex class; I’ve written a super-class extending the Express.js app.

```javascript
import passport from "passport";

// Used to serialize the user for the session:
passport.serializeUser( ( user, done ) => {
    done( null, user[ 0 ].dataValues.id );
} );

// Used to deserialize the user:
passport.deserializeUser( ( id, done ) => {
    Users.findById( id )
        .then( user => done( null, user ) )
        .catch( err => done( err ) );
} );
```

Notice that the Cookie created after requesting the `/auth/facebook/token` route has the same name (`sessionId`) as in the `express-session` middleware - I am not sure if this does changes something or not:

```javascript
import helmet           from "helmet";
import express          from "express";
import session          from "express-session";
import bodyParser       from "body-parser";

// Allows us to create sessions:
 this.app.use( session( {
    secret : "sfda",
    resave : false,
    name   : "sessionId",
    saveUninitialized : false
} ) );

// Protect express from some well-known web vulnerabilities:
this.app.use( helmet() )

// Allows express to read `x-www-form-urlencoded` data:
this.app.use( bodyParser.urlencoded( { extended : false } ) );
this.app.use( bodyParser.json() );

// Allows basic auths with `passport.js`:
this.app.use( passport.initialize() );
this.app.use( passport.session() );
```

### Facebook Token Strategy:

There’s no problem with this strategy - everything works just fine.

```javascript
import passport              from "passport";
import FacebookTokenStrategy from "passport-facebook-token";

export default ( Users, config = {} ) => {
    passport.use( new FacebookTokenStrategy( {
        clientID        : config.facebook.clientID,
        clientSecret    : config.facebook.clientSecret,
        callbackURL     : config.facebook.callbackURL,
        profileFields   : [ "id", "birthday", "displayName", "gender", "email", "picture" ],
        scope           : [ "email", "user_birthday", "user_about_me" ],
    }, ( token, refresh, profile, done ) => {
        Users.findOrCreate( {
            where : {
                token : profile.id,
            },
            defaults : {
                name        : profile.displayName,
                email       : profile.emails[ 0 ].value,
                photo       : profile.photos[ 0 ].value,
                gender      : profile.gender,
                birthday    : profile._json.birthday,
            },
        } ).then( user => {
            done( null, user );
        } ).catch( err => {
            done( err );
        } );
    } ) );
};
```

I wonder what might cause this issue - the implementation seems right for me.

**Comment by ghaiklor** [comment]
I never used `passport-facebook-token` for storing auth data in session or cookies before. Only for getting JWT, so I can't help here :(

Maybe someone else could help, you can try ask on StackOverflow, for instance.

**Comment by seb0zz** [comment]
Hi @Bartozzz had the same issue. For me it worked like this:

```javascript
app.post(
  '/auth/facebook/token',
  (req, res, next) => {
    passport.authenticate('facebook-token', (error, user, info) => {
      if (error || !user) {
        return res.status(401).json({
          error,
          info
        });
      }

      if (req.sessionID && user) {
        req.logIn(user, () => {
          return res.json({
            sessionId: cookieSignature.sign(req.sessionID, SESSION_SECRET),
            profile: user.profile
          })
        });
      }

      next();
    })(req, res, next);
  }
);
```

**Comment by Bartozzz** [comment]
Thanks! It worked like a charm.
