### ISSUE TITLE
Hi, does this api use Authorization Code Flow with Proof Key of Exchange?

### ISSUE THREAD

**Issue by 1kvnlee** [drudge/passport-facebook-token#93]
## Question
Hi, does this api use Authorization Code Flow with Proof Key of Exchange?

**Comment by ghaiklor** [comment]
You mean this one - https://github.com/drudge/passport-facebook-token/blob/master/src/index.js#L102 ?

**Comment by 1kvnlee** [comment]
Hi @ghaiklor , i would like to know if the passport-facebook-token uses the "Authorization Code Flow with Proof Key of Exchange" code verifier, code challenge. https://auth0.com/docs/flows/concepts/auth-code-pkce

**Comment by ghaiklor** [comment]
@1kvnlee we don't use Auth0 at all and I'm not recall that we were implementing it ourselves. Moreover, it seems like you do not understand the purpose of this package. We design it to fetch the profile information if you **already have a token**, not for obtaining one.

**Comment by 1kvnlee** [comment]
@ghaiklor Thanks you are right. I think I should check the react native fbsdk since it is the one issuing the access token.
